name: Quick Publish

on:
  push:
    branches:
      - 'quick-publish/**'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  quick-publish:
    name: Quick Publish
    strategy:
      matrix:
        os: [self-hosted]
        scala: [2.12.18]
        java: ["temurin:1.20.0.2"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SBT Cache
        uses: coursier/cache-action@v6
      - name: Setup Java and Scala
        uses: coursier/setup-action@v1
        with:
          jvm: ${{ matrix.java }}
          apps: sbt sbtn
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: 'arn:aws:iam::704349335716:role/nio-github-action-runner'
      - name: Quick publish
        working-directory: backend
        run: 'sbt ++${{ matrix.scala }} quickPublish'

